/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AcceptGPSLogSchema {
  latitude: number;
  longitude: number;
  speed: number;
  timestamp: Date;
  vehicleId: string;
}
