/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface VehicleHistoryLogSchema {
  from: Date;
  limit?: number;
  offset?: number;
  to: Date;
}
